<Project Sdk="Godot.NET.Sdk/4.6.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>TalismanOfDeath</RootNamespace>
    <AssemblyName>TalismanOfDeath</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);Common/**;data/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="scripts\Game\" />
    <Folder Include="scripts\UI\" />
    <Folder Include="scripts\Data\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Common\Gwergilius.Common.csproj" />
    <ProjectReference Include="data\TalismanOfDeath.Content.csproj" />
  </ItemGroup>
</Project>
