<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TalismanOfDeath.Content</RootNamespace>
    <AssemblyName>TalismanOfDeath.Content</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="*.yaml">
      <Link>data\%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>
</Project>
